server:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "standard"

kubeStateMetrics:
  enabled: false
alertmanager:
  enabled: false