kraft:
  enabled: true

controller:
  replicaCount: 1

broker:
  replicaCount: 1
  persistence:
    size: 2Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  extraEnvVars:
    - name: KAFKA_CFG_LISTENERS
      value: PLAINTEXT://:9092
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092

zookeeper:
  enabled: false